force-app/main/default/objects/Account/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <inlineHelpText>Educational Stage</inlineHelpText>
    <label>Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Högstadiet</fullName>
            </value>
            <value>
                <fullName>Mellanstadiet</fullName>
            </value>
            <value>
                <fullName>Förberedelseklass</fullName>
            </value>
            <value>
                <fullName>Børnehaveklasse/0. Klasse</fullName>
            </value>
            <value>
                <fullName>Indskolning</fullName>
            </value>
            <value>
                <fullName>Mellemtrin</fullName>
            </value>
            <value>
                <fullName>Udskolning</fullName>
            </value>
            <value>
                <fullName>10. Klasse</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <isActive>false</isActive>
                <label>All</label>
            </value>
            <value>
                <fullName>Børnehaveklasse</fullName>
                <isActive>false</isActive>
                <label>Børnehaveklasse</label>
            </value>
            <value>
                <fullName>Børnehaveklassen</fullName>
                <isActive>false</isActive>
                <label>Børnehaveklassen</label>
            </value>
            <value>
                <fullName>Lågsta</fullName>
                <isActive>false</isActive>
                <label>Lågsta</label>
            </value>
            <value>
                <fullName>TBC</fullName>
                <isActive>false</isActive>
                <label>TBC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/NAV_Type__c.field-meta.xml
<CustomField>
    <fullName>NAV_Type__c</fullName>
    <description>NAV intergration</description>
    <inlineHelpText>NAV intergration</inlineHelpText>
    <label>NAV Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Item</fullName>
                <default>true</default>
                <label>Item</label>
            </value>
            <value>
                <fullName>G/L Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Navision_Prod_No__c.field-meta.xml
<CustomField>
    <fullName>Navision_Prod_No__c</fullName>
    <externalId>true</externalId>
    <label>Navision Prod No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Quiz</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_No__c.field-meta.xml
<CustomField>
    <fullName>Product_No__c</fullName>
    <label>Product No</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Clio Online Portal</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>IF(INCLUDES(  SBQQ__Product__r.Level__c  , &quot;Högstadiet&quot;), &quot;Högstadiet&quot; + BR(), NULL)   + 
IF(INCLUDES( SBQQ__Product__r.Level__c , &quot;Mellanstadiet&quot;), &quot;Mellanstadiet&quot; + BR() , NULL)  +
IF(INCLUDES( SBQQ__Product__r.Level__c , &quot;Förberedelseklass&quot;), &quot;Förberedelseklass&quot; + BR() , NULL)  + 
IF(INCLUDES( SBQQ__Product__r.Level__c , &quot;Børnehaveklasse/0. Klasse&quot;), &quot;Børnehaveklasse/0. Klasse&quot; + BR() , NULL)  +
IF(INCLUDES( SBQQ__Product__r.Level__c , &quot;Indskolning&quot;), &quot;Indskolning&quot; + BR() , NULL)  +
IF(INCLUDES( SBQQ__Product__r.Level__c , &quot;Mellemtrin&quot;), &quot;Mellemtrin&quot; + BR() , NULL)  + 
IF(INCLUDES( SBQQ__Product__r.Level__c , &quot;Udskolning&quot;), &quot;Udskolning&quot; + BR() , NULL)  +
IF(INCLUDES( SBQQ__Product__r.Level__c , &quot;10. Klasse&quot;), &quot;10. Klasse&quot;, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product used to sell this subscription.</description>
    <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductOverViewTest.cls
@istest
public class ProductOverViewTest {

	static testmethod void testScheduler() {
	Id pricebookId = Test.getStandardPricebookId();
			Account acc = new Account();
			acc.Name = 'test';
			acc.Type = 'Prospect';
			acc.CurrencyIsoCode = 'DKK';
			acc.BillingCountry = 'Denmark';
			acc.Country_Code__c = 'DK';
			acc.Market__c = 'Denmark';
			insert acc;
	Product2 prod = new Product2();
			prod.Country_Code__c = 'DK';
			prod.CurrencyIsoCode = 'DKK';
			prod.Family = 'Portal';
			prod.IsActive = true;
			prod.Level__c = 'Indskolning';
			prod.Name = 'Billedkunstfaget.dk (1.-2. klasse)';
			prod.NAV_Type__c = 'Item';
			prod.Navision_Prod_No__c = 23100;
			prod.Product_Category__c = 'Portal';
			prod.Product_No__c = 391;
			prod.Product_Type__c = 'Clio Online Portal';
			prod.SBQQ__SubscriptionPricing__c = 'Fixed Price';
			prod.SBQQ__SubscriptionTerm__c = 12;
			prod.ProductCode = 'BKIN';
			insert prod;
			
	SBQQ__Subscription__c sub = new SBQQ__Subscription__c();
			sub.SBQQ__Account__c=acc.Id;
			sub.SBQQ__Product__c = prod.Id;
        	sub.SBQQ__Quantity__c=1;
			//sub.SBQQ__StartDate__c=date.today().adddays(-5);
			//sub.SBQQ__EndDate__c=date.today().adddays(5);
			insert sub;

			test.starttest();
			ProductOverviewBatchScheduler myClass = new ProductOverviewBatchScheduler ();   
			String chron = '0 0 23 * * ?';        
			system.schedule('Test Sched', chron, myClass);
			test.stopTest();
		}
}