force-app/main/default/objects/Account/fields/Subscription_ACV__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ACV__c</fullName>
    <description>Count all active Subscription ACV</description>
    <inlineHelpText>Count all active Subscription ACV</inlineHelpText>
    <label>Subscription ACV</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Clio Online Portal</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductOverview__c/ProductOverview__c.object-meta.xml
<CustomObject>
    <label>Product Overview</label>
    <nameField>
        <displayFormat>Product Overview {0000000}</displayFormat>
        <label>ProductOverview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Overview</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductOverview__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>ProductOverview</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductOverview__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductOverview__c/fields/Highest_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Highest_Start_Date__c</fullName>
    <label>Highest End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProductOverview__c/fields/Lowest_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Lowest_Start_Date__c</fullName>
    <label>Lowest Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProductOverview__c/fields/No_Of_Active_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Active_Subscriptions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Active Subscriptions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductOverview__c/fields/No_Of_Expired_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Expired_Subscriptions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No Of Expired Subscriptions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductOverview__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>ProductOverview</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductOverview__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT( Product__r.Product_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductOverview__c/fields/Sum_of_Subscription_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sum_of_Subscription_Amount__c</fullName>
    <label>Sum of Subscription Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Product_Overview__c.field-meta.xml
<CustomField>
    <fullName>Product_Overview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to create the related list on the Product Overview Custom Object</description>
    <label>Product Overview</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ProductOverview__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>ProductOverview__c.Product__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Product__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ProductOverview__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product used to sell this subscription.</description>
    <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Subscription_ACV__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ACV__c</fullName>
    <formula>IF(AND(SBQQ__ProrateMultiplier__c &gt; 0, ISPICKVAL( SBQQ__PricingMethod__c ,&apos;Block&apos;)) ,   (SBQQ__CustomerPrice__c / SBQQ__ProrateMultiplier__c)  , 
IF (AND (SBQQ__ProrateMultiplier__c &gt; 0, ISPICKVAL( SBQQ__PricingMethod__c ,&apos;List&apos;)), ( SBQQ__Quantity__c * (SBQQ__CustomerPrice__c /   SBQQ__ProrateMultiplier__c )), 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscription Yearly Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProductOverviewBatch.cls
//
// Rolf Davidsson Fluido DK	20201009
// Important. Class should be executed with 1
// Database.executeBatch(new ProductOverviewBatch(), 1);
// 
// Scheduler ProductOverviewBatchScheduler
//


global class ProductOverviewBatch implements Database.Batchable<sObject> {
    global Integer ProcessedAccounts = 0;
    global Integer ProcessedAccountsWithContracts = 0;
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
         //0011t00000TeIZvAAN
         //0011q00000bBzSUAA0
         //0011t00000TcpskAAB
        //return Database.getQueryLocator('SELECT ID FROM Account where id=\''+'0011q00000bBzSUAA0'+'\'');
       	 return Database.getQueryLocator('SELECT ID FROM Account');
    }
    
    global void execute(Database.BatchableContext bc, List<Account> scope){
        Id AccountId=scope[0].Id;           
        
        String currencyCode = [SELECT Id, CurrencyIsoCode FROM Account WHERE Id = :accountId].CurrencyIsoCode;
        Map<Id, Product2> prdsWithId = new Map<Id, Product2>(
          [SELECT Id, Name FROM Product2 WHERE CurrencyIsoCode = :currencyCode AND IsActive = TRUE AND Product_Type__c='Clio Online Portal']
        );      
        
      //  list<ProductOverview__c> toDel = [select id from ProductOverview__c where account__c=:AccountId];
      //  delete toDel;
        
		list<SBQQ__Subscription__c> subRecs = [SELECT Id, SBQQ__Product__c, SBQQ__ProductName__c,Subscription_ACV__c,
                                            SBQQ__StartDate__c, SBQQ__EndDate__c, Is_Active__c FROM SBQQ__Subscription__c
                                            WHERE SBQQ__Account__c =:AccountId AND SBQQ__Product__r.Product_Type__c='Clio Online Portal'];
		ProcessedAccounts++;
        if (subRecs.isEmpty()) return;
        
        Map<Id, List<SBQQ__Subscription__c>> prdIdToSubsMap = new Map<Id, List<SBQQ__Subscription__c>>();
        for (SBQQ__Subscription__c s : subRecs) {
          if (prdIdToSubsMap.containsKey(s.SBQQ__Product__c)) {
            List<SBQQ__Subscription__c> subs = prdIdToSubsMap.get(s.SBQQ__Product__c);
            subs.add(s);
            prdIdToSubsMap.put(s.SBQQ__Product__c, subs);
          } else {
            prdIdToSubsMap.put(
              s.SBQQ__Product__c,
              new List<SBQQ__Subscription__c>{ s }
            );
          }
        }
        
        map<String,ProductOverview__c> productsOnAccount = new map<String,ProductOverview__c>();
        for (Product2 p : prdsWithId.values()) {
            ProductOverview__c A = new ProductOverview__c();
            A.No_Of_Active_Subscriptions__c=0;
            A.No_Of_Expired_Subscriptions__c=0;
            A.ExternalId__c =AccountId +'|'+p.Id;
            A.Product__c = p.Id;
            A.Account__c = AccountId;
            A.Sum_of_Subscription_Amount__c=0;
            productsOnAccount.put (AccountId +'|'+p.Id, A);
        }
        map<String,ProductOverview__c> objOnAccountProduct = new map<String,ProductOverview__c>();
        for (Product2 p : prdsWithId.values()) {
              ProductOverview__c po = productsOnAccount.get(AccountId +'|'+p.Id);
              if (prdIdToSubsMap.containsKey(p.Id)) {
                for (SBQQ__Subscription__c su : prdIdToSubsMap.get(p.Id)) {
                  po.Product_Name__c = su.SBQQ__ProductName__c;
                  po.Purchased__c = true;
                  // Highest End Date
                  // if (su.SBQQ__StartDate__c>po.Highest_Start_Date__c || po.Highest_Start_Date__c==null) po.Highest_Start_Date__c = su.SBQQ__StartDate__c; 
                    if (su.Is_Active__c==true) {
                      if (su.SBQQ__EndDate__c>po.Highest_Start_Date__c || po.Highest_Start_Date__c==null) po.Highest_Start_Date__c = su.SBQQ__EndDate__c;                     
                      if (su.SBQQ__StartDate__c<po.Lowest_Start_Date__c || po.Lowest_Start_Date__c==null) po.Lowest_Start_Date__c = su.SBQQ__StartDate__c;
                    }
                  po.Sum_of_Subscription_Amount__c =po.Sum_of_Subscription_Amount__c+su.Subscription_ACV__c;
                  if (Date.today() > su.SBQQ__EndDate__c || Date.Today() <su.SBQQ__StartDate__c) {
                      po.No_Of_Expired_Subscriptions__c++;     
                  }
                  if (Date.today() < su.SBQQ__EndDate__c && Date.Today() > su.SBQQ__StartDate__c) {
                       po.No_Of_Active_Subscriptions__c++;     
                  }
                }
              } else {
                po.Product_Name__c = p.Name;
                po.Purchased__c = false;
              }
              objOnAccountProduct.put(po.ExternalId__c,po);
        }   
        
        list<ProductOverview__c> target = new list<ProductOverview__c>();
        for (Product2 p : prdsWithId.values()) {
            target.add(productsOnAccount.get(AccountId +'|'+p.Id));
        }              
        ProcessedAccountsWithContracts++;
        if (!target.isEmpty()) upsert target ExternalId__c;
        
        
        list<SBQQ__Subscription__c> forUpd = new list<SBQQ__Subscription__c>();
        for (ProductOverview__c pv:target) {
            try {
                for (SBQQ__Subscription__c su : prdIdToSubsMap.get(pv.Product__c)) {                
                    system.debug('getting:'+pv.ExternalId__c);
                    su.Product_Overview__c = objOnAccountProduct.get(pv.ExternalId__c).Id;
                    forUpd.add(su);
                }
            }
                catch (exception e) {
                    system.debug('HANDLED ERROR:'+e.getMessage());
            }
                                
        }
        if (!forUpd.isEmpty()) update forUpd;


    }

 global void finish(Database.BatchableContext bc){
     system.debug('ProductOverviewBatch ====================================================');
     system.debug('ProductOverviewBatch completed. Processed accounts without contracts'+ProcessedAccounts);
     system.debug('ProductOverviewBatch completed. Processed accounts with contracts '+ProcessedAccountsWithContracts);
     system.debug('ProductOverviewBatch ====================================================');
 }    

}