force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Invoice Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/fields/Blanket_Order_Delete__c.field-meta.xml
<CustomField>
    <fullName>Blanket_Order_Delete__c</fullName>
    <label>Blanket Order Delete</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Item_Serie_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Serie_Number__c</fullName>
    <label>Item Serie Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Number</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Partner_Discount__c.field-meta.xml
<CustomField>
    <fullName>Partner_Discount__c</fullName>
    <label>Partner Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>SFDC_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(Product__r.Product_Type__c)</formula>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Sales_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Type_Code__c</fullName>
    <label>Sales Type Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Type_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Total_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount__c</fullName>
    <label>Total Discount (%)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Total_Discount_incl_Partner__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount_incl_Partner__c</fullName>
    <label>Total Discount incl. Partner (%)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Yearly_Product_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Product_Order_Value__c</fullName>
    <label>Yearly Product Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Clio_First_invoice_date__c.field-meta.xml
<CustomField>
    <fullName>Clio_First_invoice_date__c</fullName>
    <description>This field indicates the first day the invoice is sent / start for the customer. Automatically copied from the Quote object.</description>
    <label>First Invoice date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sent_for_Invoicing_Date_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Sent_for_Invoicing_Date_Stamp__c</fullName>
    <label>Sent for Invoicing Date Stamp</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Yearly_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Order_Value__c</fullName>
    <formula>Opportunity.Clio_Yearly_Opportunity_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Yearly Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Sales_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Type_Code__c</fullName>
    <label>Sales Type Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SALE-NEW</fullName>
            </value>
            <value>
                <fullName>SALE-UPSELL</fullName>
            </value>
            <value>
                <fullName>SALE-RESALE</fullName>
            </value>
            <value>
                <fullName>SALE-REBILL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount__c</fullName>
    <description>NAV Integration (?)</description>
    <formula>SBQQ__QuoteLine__r.SBQQ__TotalDiscountRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Discount (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Discount_incl_Partner__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount_incl_Partner__c</fullName>
    <description>NAV Integration</description>
    <formula>SBQQ__QuoteLine__r.Total_Discount_incl_Partner__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Discount incl. Partner (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Yearly_Product_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Product_Order_Value__c</fullName>
    <formula>SBQQ__QuoteLine__r.Yearly_Order_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Yearly Product Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Clio Online Portal</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Clio_First_invoice_date__c.field-meta.xml
<CustomField>
    <fullName>Clio_First_invoice_date__c</fullName>
    <description>This field indicates the first day the invoice is sent / start for the customer.</description>
    <label>First invoice date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PartnerDiscount__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PartnerDiscount__c</fullName>
    <description>Discount extended to the partner on this opportunity.</description>
    <inlineHelpText>Use for ex: Läromedia Discount (Discount extended to the partner on this opportunity.)</inlineHelpText>
    <label>Partner Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Partner_Discount__c.field-meta.xml
<CustomField>
    <fullName>Partner_Discount__c</fullName>
    <formula>If(
Partner_ACV__c != 0, (1 - ( Partner_ACV__c /  Customer_ACV__c )),
0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Total_Discount_incl_Partner__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount_incl_Partner__c</fullName>
    <formula>IF(SBQQ__ProratedListPrice__c == 0, 0,
IF(ISPICKVAL(SBQQ__DiscountScheduleType__c, &apos;Slab&apos;) &amp;&amp; NOT(SBQQ__Existing__c),
IF(SBQQ__Quantity__c == 0, 0, (SBQQ__ProratedListPrice__c * SBQQ__Quantity__c - SBQQ__PartnerPrice__c) / (SBQQ__Quantity__c * SBQQ__ProratedListPrice__c)),
IF(ISPICKVAL(SBQQ__DiscountScheduleType__c, &apos;Slab&apos;) &amp;&amp; SBQQ__Existing__c,
IF(SBQQ__Quantity__c == SBQQ__PriorQuantity__c, 0, (SBQQ__ProratedListPrice__c * (SBQQ__Quantity__c-SBQQ__PriorQuantity__c) - SBQQ__PartnerPrice__c) / ((SBQQ__Quantity__c-SBQQ__PriorQuantity__c) * SBQQ__ProratedListPrice__c)),
(SBQQ__ProratedListPrice__c - SBQQ__PartnerPrice__c) / SBQQ__ProratedListPrice__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Discount incl. Partner (%)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Yearly_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Order_Value__c</fullName>
    <formula>SBQQ__CustomerTotal__c / SBQQ__ProrateMultiplier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Shows the 12 month value of a deal, regardless of subscription term.</inlineHelpText>
    <label>Customer Yearly Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OrderTriggerHandler.cls
public without sharing class OrderTriggerHandler implements ITriggerHandler {
	@TestVisible private static Boolean triggerBypass = false;
    
    public Boolean isDisabled() {
        return triggerBypass;
    }
    
    public void beforeInsert(List<SObject> newItems) {
        // This is a placeholder for handlers
    }

    public void beforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        // This is a placeholder for handlers
    }

    public void beforeDelete(Map<Id, SObject> oldItems) {
        // This is a placeholder for handlers
    }

    public void afterInsert(Map<Id, SObject> newItems) {
        // This is a placeholder for handlers
    }

    public void afterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        createInvoiceLinesForActivatedOrders((Map<Id, Order>) newItems, (Map<Id, Order>) oldItems);
    }

    public void afterDelete(Map<Id, SObject> oldItems) {
        // This is a placeholder for handlers
    }

    public void afterUndelete(Map<Id, SObject> oldItems){
        // This is a placeholder for handlers
    }
    
    private void createInvoiceLinesForActivatedOrders(Map<Id, Order> newOrders, Map<Id, Order> oldOrders) {
        Map<Id, Order> activatedOrders = filterActivatedOrders(newOrders, oldOrders);
        List<OrderItem> filteredOrderProducts = filterClioOnlinePortalProducts(activatedOrders);
        System.debug('Found ' + activatedOrders.size() + ' activatedOrders and ' + filteredOrderProducts.size() + ' filteredOrderProducts');
        if (!filteredOrderProducts.isEmpty()) {
        	createInvoiceLines(filteredOrderProducts);
        }
    }
    
    private Map<Id, Order> filterActivatedOrders(Map<Id, Order> newOrders, Map<Id, Order> oldOrders) {
        Map<Id, Order> activatedOrders = new Map<Id, Order>();
        for (Order o : newOrders.values()) {
            
            if (o.Sent_for_Invoicing_Date_Stamp__c	!= null) {
                System.debug('Skipping creation of invoice lines becase "Sent for Invoicing Date Stamp" is not empty.');
            }
            if (o.Sent_for_Invoicing_Date_Stamp__c	== null &&
                o.Status == Constants.ORDER_STATUS_SENT_FOR_INVOICING && 
                oldOrders.get(o.Id).Status != Constants.ORDER_STATUS_SENT_FOR_INVOICING) {
                    activatedOrders.put(o.Id, o);
            }
        }
        return activatedOrders;
    }
    
    private void createInvoiceLines(List<OrderItem> orderProducts) {
        List<Invoice_Line__c> newInvoiceLines = new List<Invoice_Line__c>();
        for (OrderItem oi : orderProducts) {
            if (oi.SBQQ__QuotedQuantity__c > 0) {
            	newInvoiceLines.addAll(preparePositiveInvoiceLinesForOrderProduct(oi));
            } else {
                newInvoiceLines.addAll(prepareNegativeInvoiceLinesForOrderProduct(oi));
            }
        }
        insert newInvoiceLines;
    }
    
    private List<Invoice_Line__c> preparePositiveInvoiceLinesForOrderProduct(OrderItem oi) {
        return prepareInvoiceLinesForOrderProduct(oi, false);
    }
    
    @TestVisible
    private List<Invoice_Line__c> prepareNegativeInvoiceLinesForOrderProduct(OrderItem oi) {
        return prepareInvoiceLinesForOrderProduct(oi, true);
    }
    
    private List<Invoice_Line__c> prepareInvoiceLinesForOrderProduct(OrderItem oi, Boolean isNegative) {
        List<Invoice_Line__c> newInvoiceLines = new List<Invoice_Line__c>();
        Date invoiceLineStartDate = null;
        Date invoiceLineEndDate = null;
        Integer monthsCountPerInvoiceLine = getMonthsCountBasingOnBillingFrequency(oi);
        Integer i = 1;
        do {
            Invoice_Line__c newIL = new Invoice_Line__c();
            newIL.Item_Serie_Number__c = i;
            newIL.CurrencyIsoCode = oi.Order.CurrencyIsoCode;
            newIL.Sales_Type_Code__c = invoiceLineStartDate == null ? oi.Sales_Type_Code__c : Constants.SALES_TYPE_CODE_REBILL;
            newIL.Blanket_Order_Delete__c = invoiceLineStartDate != null && isNegative ? Date.today() : null;
            invoiceLineStartDate = invoiceLineStartDate == null ? oi.ServiceDate : isNegative ? invoiceLineEndDate.addDays(1) : invoiceLineStartDate.addMonths(monthsCountPerInvoiceLine);
            newIL.Start_Date__c = invoiceLineStartDate;
            invoiceLineEndDate = isNegative ? getEndDateForNegative(invoiceLineStartDate, invoiceLineEndDate, oi.EndDate, monthsCountPerInvoiceLine) : getEndDateForPositive(oi.EndDate, invoiceLineStartDate, monthsCountPerInvoiceLine);
            newIL.End_Date__c = invoiceLineEndDate;
            newIL.Shipment_Date__c = i == 1 ? getFirstDateIfNullThenSecond(oi.Order.Clio_First_invoice_date__c, oi.Order.ActivatedDate.date()) : newIL.Start_Date__c;
            newIL.Quote_Line__c = oi.SBQQ__QuoteLine__c;
            newIL.Product__c = oi.Product2Id;
            newIL.Order__c = oi.OrderId;
            newIL.Order_Product__c = oi.Id;
            newIL.Yearly_Product_Order_Value__c = oi.SBQQ__QuoteLine__c != null ? oi.SBQQ__QuoteLine__r.Yearly_Order_Value__c : null;
            newIL.Total_Discount__c = oi.SBQQ__QuoteLine__c != null ? oi.SBQQ__QuoteLine__r.SBQQ__TotalDiscountRate__c : null;
            newIL.Partner_Discount__c = oi.SBQQ__QuoteLine__c != null && oi.SBQQ__QuoteLine__r.SBQQ__Quote__c != null ? oi.SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__PartnerDiscount__c : null;
            newIL.Total_Discount_incl_Partner__c = oi.SBQQ__QuoteLine__c != null ? oi.SBQQ__QuoteLine__r.Total_Discount_incl_Partner__c : null;
            newInvoiceLines.add(newIL);
            i += 1;
        } while(oi.EndDate > invoiceLineStartDate.addMonths(monthsCountPerInvoiceLine).addDays(-1));
        return newInvoiceLines;
    }
    
    private Date getFirstDateIfNullThenSecond(Date firstDate, Date secondDate) {
        if (firstDate == null) {
            return secondDate;
        }
        return firstDate;
    }
    
    private Integer getMonthsCountBasingOnBillingFrequency(OrderItem oi) {
        Integer monthsCount = 12; // default is 1 year per Invoice Line
        if (oi.SBQQ__QuoteLine__c != null && oi.SBQQ__QuoteLine__r.SBQQ__Quote__c != null) {
            switch on oi.SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__BillingFrequency__c {
                when 'Semiannual' {
            		monthsCount = 6;
                } when 'Kvartalsvis' {
                    monthsCount = 3;
                } when 'One Time' {
                    monthsCount = 1200; // 100 years
                }
            }
        }
        return monthsCount;
    }
    
    private Date getEndDateForPositive(Date orderProductEndDate, Date invoiceLineStartDate, Integer monthsCountPerInvoiceLine) {
        if (orderProductEndDate > invoiceLineStartDate.addMonths(monthsCountPerInvoiceLine).addDays(-1)) {
            return invoiceLineStartDate.addMonths(monthsCountPerInvoiceLine).addDays(-1);
        } else {
            return orderProductEndDate;
        }
    }
    
    private Date getEndDateForNegative(Date lastInvoiceLineStartDate, Date lastInvoiceLineEndDate, Date orderProductEndDate, Integer monthsCountPerInvoiceLine) {
        if (lastInvoiceLineEndDate == null) {
            lastInvoiceLineEndDate = orderProductEndDate;
            while (lastInvoiceLineEndDate > lastInvoiceLineStartDate) {
                lastInvoiceLineEndDate = lastInvoiceLineEndDate.addMonths(-monthsCountPerInvoiceLine);
            }
        }
        return lastInvoiceLineEndDate.addMonths(monthsCountPerInvoiceLine);
    }
    
    @TestVisible
    private List<OrderItem> filterClioOnlinePortalProducts(Map<Id, Order> orders) {
        List<Order> ordersWithRelations = [
            SELECT 
                (SELECT Id,
                Order.ActivatedDate,
                Order.CurrencyIsoCode,
                Order.Clio_First_invoice_date__c,
                Sales_Type_Code__c,
                ServiceDate,
                EndDate,
                Product2Id,
                OrderId,
                SBQQ__QuotedQuantity__c,
                SBQQ__QuoteLine__r.Yearly_Order_Value__c,
                SBQQ__QuoteLine__r.SBQQ__TotalDiscountRate__c,
                SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__PartnerDiscount__c,
                SBQQ__QuoteLine__r.Total_Discount_incl_Partner__c,
                SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__BillingFrequency__c,
                SBQQ__QuoteLine__c
                FROM OrderItems
                WHERE Product2.Product_Type__c = :Constants.PRODUCT_TYPE_CLIO_ONLINE_PORTAL)
            FROM Order
            WHERE Id IN :orders.keyset()
        ];
        
        List<OrderItem> filteredItems = new List<OrderItem>();
        for (Order o : ordersWithRelations) {
            filteredItems.addAll(o.OrderItems);
        }
        return filteredItems;
    }
}